harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

information/urls.py
from django.urls import path
from .views import *

app_name = 'information'

urlpatterns = [
    path("offers/", OfferView.as_view(), name="offers"),
    path('answers/', AnswerView.as_view(), name='answers'),
    path('answers_comment/', AnswerCommentView.as_view(), name='answers_comment'),
    path('comments/', CommentView.as_view(), name='comments'),
    path('comments/category/<int:category>/', CommentsByCategoryView.as_view(), name='comments_category'),
    path('articles/', ArticlesView.as_view(), name="articles"),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/category/<slug:slug>/', ArticlesByCategoryView.as_view(), name='article_category'),
    path('articles/<slug:slug>/positive_grade/', PositiveGradeArticleView.as_view(), name='positive_grade_article'),
    path('articles/<slug:slug>/negative_grade/', NegativeGradeArticleView.as_view(), name='negative_grade_article'),
]

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

information/forms.py
from django import forms
from .models import *
from django.utils.text import slugify
from unidecode import unidecode


class OfferForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Offer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ваше предложение или пожелание'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = ['text', 'category']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True
            }),
            'category': forms.Select(attrs={
                'class': 'form-select', 'required': True
            }),
        }
        labels = {
            'text': 'Ваш отзыв',
            'category': 'Категория отзыва'
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Answer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ответ специалиста'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

information/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F, Q
from .models import *
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DetailView
from django.views.generic.edit import FormMixin
from .forms import *
import json
from django.utils.http import urlencode
from urllib.parse import unquote
from django.utils.decorators import method_decorator


menu = [
    {"title": "Главная", "alias": "main", "icon": "bi-house"},
    {"title": "Наши специалисты", "alias": "users:specialists", "icon": "bi-person"},
    {"title": "Советы психолога", "alias": "information:articles", "icon": "bi-chat-dots"},
    {"title": "Тестирование", "alias": "tests:testing", "icon": "bi-ui-checks-grid"},
    {"title": "Консультации", "alias": "events:consultations", "icon": "bi-clipboard"},
    {"title": "Тренинги", "alias": "events:trainings", "icon": "bi-briefcase"},
    {"title": "Отзывы клиентов", "alias": "information:comments", "icon": "bi-list-stars"},
    {"title": "Ваши предложения", "alias": "information:offers", "icon": "bi-lightbulb"}
]


def custom_404_view(request, exception):
    messages.error(request, "Такой страницы не существует, поэтому Вы перенаправлены на главную страницу сайта")
    return redirect('main')


class MainView(TemplateView):
    template_name = 'main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'main'
        return context


class OfferView(ListView):
    model = Offer
    template_name = 'offer/offer.html'
    context_object_name = 'offers'
    paginate_by = 3

    def get_queryset(self):
        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                return Offer.objects.prefetch_related('answer').select_related('author').order_by('-published_date')
            else:
                return (Offer.objects.filter(author=self.request.user).
                        prefetch_related('answer').select_related('author').order_by('-published_date'))
        else:
            return Offer.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'information:offers'
        context['form'] = OfferForm()
        context['answer_form'] = AnswerForm()
        context['is_blacklisted'] = self.request.user.groups.filter(name='Черный список').exists()
        return context

    def post(self, request, *args, **kwargs):
        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.author = request.user
            offer.save()
            messages.success(request, 'Ваше предложение успешно добавлено!')
            page = request.POST.get('page', 1)
            return redirect(f"{reverse('information:offers')}?page={page}")


class CommentView(ListView):
    model = Comment
    template_name = 'comment/comment.html'
    context_object_name = 'comments'
    paginate_by = 3

    def get_queryset(self):
        if self.request.user.is_staff:
            return (Comment.objects.prefetch_related('answer').
                    select_related('author').order_by('-published_date'))
        else:
            return (Comment.objects.filter(status=2).prefetch_related('answer').
                    select_related('author').order_by('-published_date'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'information:comments'
        context['form'] = CommentForm()
        context['answer_form'] = AnswerForm()
        context['is_blacklisted'] = self.request.user.groups.filter(name='Черный список').exists()
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            messages.success(request, 'Ваш отзыв добавлен и находится на модерации!')
            page = request.POST.get('page', 1)
            return redirect(f"{reverse('information:comments')}?page={page}")


class ClientCommentView(ListView):
    model = Comment
    template_name = 'client/client_comment.html'
    context_object_name = 'client_comments'

    def get_queryset(self):
        return (Comment.objects.filter(author=self.request.user).prefetch_related('answer').
                select_related('author').order_by('-published_date'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'users:client_comments'
        return context


class AnswerView(ListView):
    model = Answer
    context_object_name = 'answers'

    def get_queryset(self):
        return Answer.objects.select_related('author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_alias'] = 'information:answers'
        context['form'] = AnswerForm()
        return context

    def post(self, request, *args, **kwargs):
        form = AnswerForm(request.POST)
        if form.is_valid():
            answers = form.save(commit=False)
            answers.author = request.user
            offer_id = request.POST.get('offer_id')
            offer = get_object_or_404(Offer, id=offer_id)
            answers.save()
            offer.answer.add(answers)
            messages.success(request, 'Ваш ответ добавлен!')
            page = request.POST.get('page', 1)
            return redirect(f"{reverse('information:offers')}?page={page}")


class AnswerCommentView(ListView):
    model = Answer
    context_object_name = 'answers_comment'

    def get_queryset(self):
        return Answer.objects.select_related('author')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_alias'] = 'information:comment'
        context['form'] = AnswerForm()
        return context

    def post(self, request, *args, **kwargs):
        form = AnswerForm(request.POST)
        if form.is_valid():
            answers = form.save(commit=False)
            answers.author = request.user
            comment_id = request.POST.get('comment_id')
            comment = get_object_or_404(Comment, id=comment_id)
            answers.save()
            comment.answer.add(answers)
            messages.success(request, 'Ваш ответ добавлен!')
            page = request.POST.get('page', 1)
            return redirect(f"{reverse('information:comments')}?page={page}")


class ArticlesView(ListView):
    model = Article
    template_name = 'article/articles.html'
    context_object_name = 'articles'
    paginate_by = 4

    def get_queryset(self):
        if self.request.user.is_staff:
            queryset = (Article.objects.prefetch_related('positive_grade', 'negative_grade').
                        select_related('category').
                        order_by("-published_date"))
        else:
            queryset = (Article.objects.filter(status=1).
                        prefetch_related('positive_grade', 'negative_grade').
                        select_related('category').
                        order_by("-published_date"))
        search_query = unquote(self.request.GET.get("search", ""))
        if search_query:
            query = Q(title__icontains=search_query) | Q(text__icontains=search_query)
            queryset = queryset.filter(query)
        queryset = queryset.distinct().order_by("-published_date")
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'information:articles'
        search_query = unquote(self.request.GET.get("search", ""))
        context['search_query'] = urlencode({'search': search_query})
        context['categories'] = Category.objects.order_by("name")
        return context


class ArticlesByCategoryView(ListView):
    model = Article
    template_name = 'article/articles.html'
    context_object_name = 'articles'
    paginate_by = 4

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        if self.request.user.is_staff:
            queryset = (Article.objects.filter(category__slug=self.kwargs['slug']).
                        prefetch_related('positive_grade', 'negative_grade').
                        select_related('category').
                        order_by("-published_date"))
        else:
            queryset = (Article.objects.filter(status=1, category__slug=self.kwargs['slug']).
                        prefetch_related('positive_grade', 'negative_grade').
                        select_related('category').
                        order_by("-published_date"))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'information:articles'
        context['categories'] = Category.objects.order_by("name")
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'

    def get_queryset(self):

information/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Центр психологической помощи 'Гармония'"/>
    <meta name="keywords" content="Психологическая помощь" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/emblema.jpg' %}"/>
    {% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% endblock %}
  </head>

  <body>
    <header style="background-color: #35c0f3;">
    {% block header %}
      <div class="container-fluid d-flex flex-column flex-lg-row justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <img src="{% static 'images/Гармония.png' %}" alt="ЛОГОТИП" style="height: 100px;">
          <h1 class="fst-italic text-start p-2 text-white">Центр психологической помощи "Гармония"</h1>
        </div>
        <span class="text-end p-3 d-flex align-items-center">
          {% if user.is_authenticated %}
            {% if user.avatar %}
              <img src="{{ user.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2" style="max-width: 50px;">
            {% else %}
              <span class="rounded-circle bg-success text-white d-flex align-items-center justify-content-center m-2 fs-5"
                   style="width: 50px; height: 50px;">
                <span>{{ user.username|slice:":1" }}</span>
              </span>
            {% endif %}
            {% if user.is_staff == False %}
              <a class="me-5 text-light fs-5" href="{% url 'users:client' user.pk %}">{{ user.username }}</a>
            {% else %}
              <a class="me-5 text-light fs-5" href="{% url 'users:personal' user.pk %}">{{ user.username }}</a>
            {% endif %}
              <a class="nav-link me-3" href="{% url 'users:logout' %}">
                <span class="badge text-bg-primary fs-6">Выйти</span>
              </a>
          {% else %}
            <a class="nav-link me-3" href="{% url 'users:login' %}">
              <span class="badge text-bg-primary fs-6">Вход</span>
            </a>
            <a class="nav-link me-3" href="{% url 'users:register' %}">
              <span class="badge text-bg-primary fs-6">Регистрация</span>
            </a>
          {% endif %}
        </span>
      </div>
    {% endblock %}
    </header>

    <main>
      <nav>
        {% block nav %}
            {% include 'menu.html' %}
        {% endblock %}
      </nav>
      {% block content %} {% endblock %}
    </main>

    <div class="position-fixed top-0 end-0 w-50 p-3" style="z-index: 11">
      {% if messages %}
        {% for message in messages %}
          <div class="alert {% if message.tags == 'error' %}alert-danger
                      {% elif message.tags == 'success' %}alert-primary{% endif %}
                      alert-dismissible fade show" role="alert" aria-live="assertive" aria-atomic="true">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <footer style="background-color: #35c0f3;">
      {% block footer %}
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-lg-0">
            <h5>Контакты:</h5>
            <ul class="list-unstyled">
              <li>
                <i class="bi bi-telephone-fill"></i> +7 (111) 000-00-00
              </li>
              <li>
                <i class="bi bi-house-fill"></i> г. Севастополь, ул. Айвовая
              </li>
            </ul>
            <h5>Режим работы:</h5>
            <ul class="list-unstyled">
              <li>
                Пн-Пт: <i class="bi bi-clock-fill"></i> 9:00 - 18:00
                <i class="bi bi-basket-fill"></i> 12:00 - 13:00
              </li>
              <li>
                Сб-Вс: <i class="bi bi-clock-fill"></i> 11:00 - 15:00
              </li>
            </ul>
          </div>
          <div class="col-lg-6 col-md-12 mb-4 mb-lg-0">
            <div class="map-container">
              <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af570e5d385249b7ace9bd2e5337d12e7d52fd89cddaef1adc1c9cd2e1ead58be&amp;width=350&amp;height=180&amp;lang=ru_RU&amp;scroll=true"></script>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
    let correctAnswers = 0;
    let timer;
    let timeLeft;

    function startTimer() {
        const timerTextElement = document.getElementById('timer_text');
        const timerElement = document.getElementById('timer');
        timeLeft = parseInt(timerElement.innerText, 10);

        timerTextElement.innerText = `Оставшееся время в секундах:`;
        timerElement.innerText = timeLeft;

        timer = setInterval(() => {
            if (timeLeft > 0) {
                timeLeft--;
                timerElement.innerText = timeLeft;
            } else {
                clearInterval(timer);
                finishTest(correctAnswers); // Завершение теста при истечении времени
            }
        }, 1000);
    }

    function answer(currentQuestionId, totalQuestions, correctAnswer) {

        const selectedAnswer = document.querySelector('input[name="question' + currentQuestionId + '"]:checked');
        if (!selectedAnswer) {
            alert('!!! ВЫ НЕ ВЫБРАЛИ ВАРИАНТ ОТВЕТА !!!');
            return;
        }
        if (selectedAnswer.value === correctAnswer) {
            correctAnswers += 1;
        }
        document.getElementById('question' + currentQuestionId).style.display = 'none';
        if (currentQuestionId < totalQuestions) {
            document.getElementById('question' + (currentQuestionId + 1)).style.display = 'block';
        } else {
            finishTest(correctAnswers);
        }
    }
    function finishTest(correctAnswers) {

        clearInterval(timer);
        const questions = document.querySelectorAll('[id^="question"]');
        questions.forEach(question => {
            question.style.display = 'none';
        });

        const csrfToken = document.getElementById('csrf_token').value;
        const score = correctAnswers;

        const currentUrl = window.location.href;
        const resultUrl = currentUrl + 'result/';

        fetch(resultUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrfToken
            },
            body: JSON.stringify({ score: score })
        })

        .then(response => response.json())
        .then(data => {
            if (data.success) {
                document.getElementById('result-container').style.display = 'block';
                document.getElementById('balls').innerText = `Ваш результат в балах - ${correctAnswers}.`;
                document.getElementById('result').innerHTML = data.result;
            }
        })
    }
    window.onload = function() {
        startTimer();
    };
  </script>
  </body>
</html>

information/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center m-2 text-primary">Добро пожаловать!</h1>
        <p class="fst-italic text-center m-2 fs-5">
            В нашем Центре мы понимаем, что каждый из нас сталкивается с трудностями,
            которые могут затруднить жизнь и повлиять на общее самочувствие.
            Мы готовы поддержать вас на пути к эмоциональному благополучию и гармонии.
        </p>
        <h2 class="text-center m-2 text-success">Почему выбирают нас?</h2>
        <div class="row mt-4 text-center">
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-success">Профессионализм и опыт</h5>
                        <p class="fst-italic card-text">
                            Наши специалисты — это команда высококвалифицированных психологов
                            с многолетним опытом работы. В нашем центре вы найдете поддержку, понимание и заботу.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-success">Индивидуальный подход</h5>
                        <p class="fst-italic card-text">
                            Каждая история уникальна, и мы это понимаем.
                            Наша цель — не только помочь вам справиться с текущими трудностями,
                            но и научить вас справляться с проблемами в будущем.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-success">Безопасная и поддерживающая среда</h5>
                        <p class="fst-italic card-text">
                            В нашем центре вы можете говорить о своих чувствах и переживаниях без страха осуждения.
                            Мы гарантируем полную конфиденциальность и уважение к вашему личному пространству.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <p class="text-center fst-italic m-2 fs-5">
            Если вы чувствуете, что вам нужна поддержка, не стесняйтесь обратиться к нам.
            Мы готовы выслушать вас и предложить решения, которые помогут вам вернуться к полноценной жизни.
            Наша команда поможет вам разобраться в ваших чувствах, найти пути выхода из сложных ситуаций
            и научиться справляться с трудностями.
        </p>
        <h3 class="text-center m-2 text-primary">Ваше благополучие — наша приоритетная задача!</h3>
        <h3 class="text-center m-2 text-primary">Начните свой путь к эмоциональному здоровью вместе с нами!</h3>
    </div>
{% endblock %}

information/templates/menu.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block nav %}

<nav class="navbar navbar-expand-lg bg-body-tertiary py-1">
<div class="container-fluid">
    <div class="d-flex flex-column flex-lg-row justify-content-around p-3">
        {% for item in menu %}
            <a href="{% url item.alias %}"
                class="btn {% if item.alias == page_alias %}btn-success
                           {% else %}btn-primary{% endif %}
                           d-flex align-items-center justify-content-between m-1">
            <span><i class="bi {{ item.icon }} me-2"></i>{{ item.title }}</span>
            </a>
        {% endfor %}
    </div>
</div>
</nav>

{% endblock %}