events/urls.py
from django.urls import path
from .views import *

app_name = 'events'

urlpatterns = [
    path("consultations/", ConsultationsView.as_view(), name="consultations"),
    path('consultations/<int:pk>/update/', UpdateConsultationClientView.as_view(), name='consultation_update'),
    path('consultations/<int:pk>/cancel/', CancelConsultationClientView.as_view(), name='consultation_cancel'),
    path("trainings/", TrainingsView.as_view(), name="trainings"),
    path("trainings/<int:pk>/update/", UpdateTrainingClientView.as_view(), name="training_update"),
    path('trainings/<int:pk>/cancel/', CancelTrainingClientView.as_view(), name='training_cancel'),
]

harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

information/models.py
from django.db import models
from users.models import *
from events.models import *
from django.utils.text import slugify
from unidecode import unidecode
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from tinymce.models import HTMLField


class Article(models.Model):
    STATUS_CHOICES = (
        (1, 'Опубликовано'),
        (0, 'Черновик'),
    )
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    text = HTMLField(verbose_name='Текст')
    slug = models.SlugField(unique=True, verbose_name='Адрес страницы')
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        related_name='article',
        null=True,
        blank=True,
        default=None,
        verbose_name='Категория'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    positive_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='plus',
        blank=True,
        verbose_name='Положительные оценки')
    negative_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='minus',
        blank=True,
        verbose_name='Отрицательные оценки')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_by_slug", args=[str(self.slug)])

    def save(self, *args, **kwargs):
        title = self.title.lower().replace(' ', '_')
        slug = slugify(unidecode(title))
        self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True, verbose_name='Адрес страницы'
    )

    def save(self, *args, **kwargs):
        name = self.name.lower().replace(' ', '_')
        slug = slugify(unidecode(name))
        self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("article_by_category", args=[str(self.slug)])

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Offer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='offer',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='offer_answer',
        verbose_name='Ответ'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Предложение, пожелание"
        verbose_name_plural = "Предложения, пожелания"


class Comment(models.Model):
    STATUS_CHOICES = [
        (0, 'На модерации'),
        (1, 'Отклонен'),
        (2, 'Опубликован'),
    ]
    CATEGORY_CHOICES = [
        (0, 'Общая оценка'),
        (1, 'Оценка специалиста'),
        (2, 'Оценка статьи'),
        (3, 'Оценка тренинга'),
    ]
    author = models.ForeignKey(
        'users.MyUser',
        related_name='comment',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='comment_answer',
        verbose_name='Ответ'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')
    category = models.IntegerField(
        choices=CATEGORY_CHOICES,
        default=0,
        verbose_name='Категория отзыва'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )

    def __str__(self):
        return f'{self.category} - {self.text}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Answer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='answer_author',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return f'{self.author.username} - {self.text}'

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

users/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db import models
from tinymce.models import HTMLField


class MyUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='avatars/users',
        blank=True,
        null=True,
        verbose_name='Аватар'
    )
    date_birth = models.DateField(
        blank=True,
        null=True,
        default=None,
        verbose_name='Дата рождения'
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Телефон'
    )
    job_title = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Должность'
    )
    job_speciality = HTMLField(
        blank=True,
        null=True,
        verbose_name='Направления работы'
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Education(models.Model):
    STATUS_CHOICES = [
        (1, 'Высшее образование'),
        (2, 'Повышение квалификации'),
        (3, 'Семинар'),
        (4, 'Обучающий курс'),
        (0, 'Другое'),
    ]
    educational_institution = models.CharField(
        max_length=200,
        verbose_name='Учебное заведение'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    speciality = models.TextField(
        verbose_name='Специальность'
    )
    year = models.CharField(
        max_length=4,
        verbose_name='Год окончания'
    )
    photo = models.ImageField(
        upload_to='diplomes/',
        blank=True,
        null=True,
        verbose_name=''
    )
    psychologist = models.ForeignKey(
        'users.MyUser',
        on_delete=models.CASCADE,
        related_name='psychologist',
        verbose_name='Психолог'
    )

    def __str__(self):
        return f'{self.educational_institution} ({self.status}) - {self.year}'

    class Meta:
        verbose_name = "Образование"
        verbose_name_plural = "Образование"

users/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model
from django import forms
from .models import *


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}),
        label='Email'
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}),
        label='Имя пользователя'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}),
        label='Подтверждение пароля'
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя или email'}),
        label='Имя пользователя'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )


class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'first_name', 'last_name', 'date_birth', 'email', 'phone', 'avatar']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
            'avatar': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class PersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'date_birth', 'email', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email

users/templates/client/change_password.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    смена пароля {{ user.username }}
{% endblock %}

{% block client_content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="text-center">Смена пароля</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:client_update' user.pk %}" class="btn btn-danger">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/client/client_comment.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Отзывы {{ user.username }}
{% endblock %}

{% block client_content %}
    <div class="container">
        <h4 class="card-text text-center text-success fst-italic">Ваши отзывы</h4>
        {% for comment in client_comments %}
            <div class="bg-light m-1 p-3 rounded">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        {{ comment.published_date|date:"d M Y H:i" }}
                    </small>
                    <small class="text-muted">
                        <i class="bi {% if comment.status == 0 %}bi-exclamation-circle text-warning
                                     {% elif comment.status == 1 %}bi bi-x-circle text-danger
                                     {% else %} bi bi-check-circle text-success
                                     {% endif %} me-1"></i>
                        {{ comment.get_status_display }}
                    </small>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-list me-1"></i>
                        {{ comment.get_category_display }}
                    </small>
                </div>
                <div class="mb-2">{{ comment.text }}</div>
            </div>
            {% include 'answer/comment_answer_include.html' %}
        {% endfor %}
    </div>
{% endblock %}

users/templates/client/client_menu_include.html
<div class="col-md-3 mb-3 align-self-start d-flex flex-column">
    <a href="{% url 'users:client' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-house m-2"></i>Личный кабинет</span>
    </a>
    <a href="{% url 'users:client_update' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_update' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-pencil m-2"></i>Редактировать данные</span>
    </a>
    <a href="{% url 'users:client_comments' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_comments' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-stars m-2"></i>Мои отзывы</span>
    </a>
    <a href="{% url 'users:client_consultations' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_consultations' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-clipboard-data m-2"></i>Мои консультации</span>
    </a>
    <a href="{% url 'users:client_trainings' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_trainings' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-briefcase-fill m-2"></i>Мои тренинги</span>
    </a>
    <a href="{% url 'users:client_testing' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:client_testing' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-ui-checks m-2"></i>Мои тесты</span>
    </a>
</div>

users/templates/client/client_update.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Редактирование {{ user.username }}
{% endblock %}

{% block client_content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-text text-center text-success fst-italic">Измените необходимые данные</h4>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-success m-2">Сохранить</button>
                <a href="{% url 'users:client' user.pk %}" class="btn btn-danger m-2">Отмена</a>
            </div>
        </form>
        <a href="{% url 'users:change_password' %}" class="btn btn-info m-2">Изменить пароль</a>
    </div>
</div>
{% endblock %}

users/templates/client/consultation_client.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Консультации {{ user.username }}
{% endblock %}

{% block client_content %}
    <div class="container">
        <h4 class="card-text text-center text-success fst-italic">Ваши индивидуальные консультации</h4>
        {% for consultation in client_consultations %}
            <div class="bg-light m-1 p-3 rounded">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        {{consultation.date}}, {{ consultation.date|date:"l" }}, {{consultation.time|time:'H:i'}}
                    </small>
                    <small class="text-muted">
                        <i class="bi {% if consultation.status == 2 %}bi-exclamation-circle text-warning
                                     {% elif consultation.status == 1 %}bi bi-x-circle text-danger
                                     {% else %} bi bi-check-circle text-success
                                     {% endif %} me-1"></i>
                        {{ consultation.get_status_display }}
                    </small>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="mb-2">
                        <small class="text-muted">
                            <i class="bi bi-person-fill me-1"></i>
                            Специалист:
                        </small>
                        {{consultation.psychologist.first_name}}
                        {{consultation.psychologist.last_name}} -
                        {{consultation.psychologist.job_title}}
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="mb-2">
                        <small class="text-muted">
                            <i class="bi bi-chat me-1"></i>
                            Причина обращения к психологу:
                        </small>
                    </div>
                </div>
                <div class="m-2">
                    {{consultation.description}}
                </div>
                {% if consultation.status == 2 %}
                    <div class="d-flex justify-content-end align-items-center mb-2">
                        <div class="mb-2">
                            <small class="text-muted">
                                <form action="{% url 'events:consultation_cancel' consultation.pk %}"
                                      method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="btn btn-danger btn-block m-1"
                                            onclick="return confirm('Вы уверены, что хотите отменить эту консультацию?');">
                                        <i class="bi bi-x-circle m-1"></i>
                                        Отменить
                                    </button>
                                </form>
                            </small>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/client/testing_client.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Тестирование {{ user.username }}
{% endblock %}

{% block client_content %}
    <div class="container">
        <h4 class="card-text text-center text-success fst-italic">Результаты Ваших тестов</h4>
        {% for test in client_tests %}
            <div class="bg-light m-1 p-3 rounded">
                <div class="d-flex justify-content-end align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        {{ test.testing_date|date:"d M Y H:i" }}
                    </small>
                </div>
                <div class="d-flex justify-content-end align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-bar-chart-line me-1"></i>
                        Набранные балы - {{ test.balls }}
                    </small>
                </div>
                <h4 class="text-center"><u>"{{ test.name }}"</u></h4>
                <h6>{{test.result|safe}}</h6>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/client/training_client.html
{% extends 'client/client.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Тренинги {{ user.username }}
{% endblock %}

{% block client_content %}
    <div class="container">
        <h4 class="card-text text-center text-success fst-italic">Ваши тренинги</h4>
        {% for training in client_trainings %}
            <div class="bg-light m-1 p-3 rounded">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <small class="text-muted">
                        <i class="bi bi-clock me-1"></i>
                        {{training.date}}, {{ training.date|date:"l" }}, {{training.time|time:'H:i'}}
                    </small>
                    <small class="text-muted">
                        <i class="bi {% if consultation.status == 0 %}bi-exclamation-circle text-warning
                                     {% else %} bi bi-check-circle text-success
                                     {% endif %} me-1"></i>
                        {{ training.get_status_display }}
                    </small>
                </div>
                <h5 class="text-center">Тренинг "{{training.name}}"</h5>
                <div class="row align-items-center">
                    <div class="col-md-4 align-self-start">
                        <small class="text-muted">
                            <i class="bi bi-person-fill me-1"></i>
                            Ведущие тренинга:
                        </small>
                    </div>
                    <div class="col-md-8 align-self-start">
                        {% for psychologist in training.psychologists.all %}
                            <div class="mb-2">
                                {{psychologist.first_name}}
                                {{psychologist.last_name}} -
                                {{psychologist.job_title}}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% for psychologist in training.psychologists.all %}
                    {% if psychologist.job_title == 'Детский психолог' %}
                        <div class="mb-2">
                            <small class="text-muted">
                            <i class="bi bi-person-fill-add me-1"></i>
                            В тренинге принимает участие Ваш ребенок:
                            </small>
                        </div>
                        <div class="m-2">
                            {{user.job_speciality|safe}}
                        </div>
                    {% endif %}
                {% endfor %}
                {% if training.status == 0 %}
                    <div class="d-flex justify-content-end align-items-center">
                        <div>
                            <small class="text-muted">
                                <form action="{% url 'events:training_cancel' training.pk %}"
                                      method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="btn btn-danger btn-block"
                                            onclick="return confirm('Вы уверены, что не хотите участвовать в мероприятии?');">
                                        <i class="bi bi-x-circle m-1"></i>
                                        Не буду участвовать
                                    </button>
                                </form>
                            </small>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}