harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

information/urls.py
from django.urls import path
from .views import *

app_name = 'information'

urlpatterns = [
    path("offers/", OfferView.as_view(), name="offers"),
    path('answers/', AnswerView.as_view(), name='answers'),
    path('answers_comment/', AnswerCommentView.as_view(), name='answers_comment'),
    path('comments/', CommentView.as_view(), name='comments'),
    path('comments/category/<int:category>/', CommentsByCategoryView.as_view(), name='comments_category'),
    path('articles/', ArticlesView.as_view(), name="articles"),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/category/<slug:slug>/', ArticlesByCategoryView.as_view(), name='article_category'),
    path('articles/<slug:slug>/positive_grade/', PositiveGradeArticleView.as_view(), name='positive_grade_article'),
    path('articles/<slug:slug>/negative_grade/', NegativeGradeArticleView.as_view(), name='negative_grade_article'),
]

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

information/models.py
from django.db import models
from users.models import *
from events.models import *
from django.utils.text import slugify
from unidecode import unidecode
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from tinymce.models import HTMLField


class Article(models.Model):
    STATUS_CHOICES = (
        (1, 'Опубликовано'),
        (0, 'Черновик'),
    )
    title = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Заголовок'
    )
    text = HTMLField(verbose_name='Текст')
    slug = models.SlugField(unique=True, verbose_name='Адрес страницы')
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        related_name='article',
        null=True,
        blank=True,
        default=None,
        verbose_name='Категория'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    views = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    positive_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='plus',
        blank=True,
        verbose_name='Положительные оценки')
    negative_grade = models.ManyToManyField(
        'users.MyUser',
        related_name='minus',
        blank=True,
        verbose_name='Отрицательные оценки')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_by_slug", args=[str(self.slug)])

    def save(self, *args, **kwargs):
        title = self.title.lower().replace(' ', '_')
        slug = slugify(unidecode(title))
        self.slug = slug
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name='Категория'
    )
    slug = models.SlugField(
        unique=True, verbose_name='Адрес страницы'
    )

    def save(self, *args, **kwargs):
        name = self.name.lower().replace(' ', '_')
        slug = slugify(unidecode(name))
        self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("article_by_category", args=[str(self.slug)])

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Offer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='offer',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='offer_answer',
        verbose_name='Ответ'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Предложение, пожелание"
        verbose_name_plural = "Предложения, пожелания"


class Comment(models.Model):
    STATUS_CHOICES = [
        (0, 'На модерации'),
        (1, 'Отклонен'),
        (2, 'Опубликован'),
    ]
    CATEGORY_CHOICES = [
        (0, 'Общая оценка'),
        (1, 'Оценка специалиста'),
        (2, 'Оценка статьи'),
        (3, 'Оценка тренинга'),
    ]
    author = models.ForeignKey(
        'users.MyUser',
        related_name='comment',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    answer = models.ManyToManyField(
        'information.Answer',
        blank=True,
        related_name='comment_answer',
        verbose_name='Ответ'
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')
    category = models.IntegerField(
        choices=CATEGORY_CHOICES,
        default=0,
        verbose_name='Категория отзыва'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )

    def __str__(self):
        return f'{self.category} - {self.text}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Answer(models.Model):
    author = models.ForeignKey(
        'users.MyUser',
        related_name='answer_author',
        verbose_name='Автор',
        on_delete=models.SET_NULL,
        null=True
    )
    published_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return f'{self.author.username} - {self.text}'

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

information/forms.py
from django import forms
from .models import *
from django.utils.text import slugify
from unidecode import unidecode


class OfferForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Offer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ваше предложение или пожелание'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = ['text', 'category']
        widgets = {
            'text': forms.Textarea(attrs={
                'class': 'form-control', 'rows': 5, 'id': 'id_text', 'required': True
            }),
            'category': forms.Select(attrs={
                'class': 'form-select', 'required': True
            }),
        }
        labels = {
            'text': 'Ваш отзыв',
            'category': 'Категория отзыва'
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance


class AnswerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Answer
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'id': 'id_text', 'required': True}),
        }
        labels = {'text': 'Ответ специалиста'}

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        return instance

information/templates/comment/comment.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Отзывы
{% endblock %}

{% block content %}
    <div class="container">
        {% if user.is_staff %}
            {% include 'comment/comment_for_personal_include.html' %}
            {% if page_obj.has_other_pages %}
                {% include 'pagination_include.html' %}
            {% endif %}
        {% else %}
            {% include 'comment/comment_for_client_include.html' %}
            {% if page_obj.has_other_pages %}
                {% include 'pagination_include.html' %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

information/templates/comment/comment_for_client_include.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% if user.is_authenticated %}
    {% if is_blacklisted %}
        <h2 class="text-center m-2 text-danger">
            К сожалению, Вы находитесь в черном списке и не можете оставлять отзывы
        </h2>
    {% else %}
        <h1 class="text-center m-2 text-primary">Оцените нашу работу!</h1>
        <form method="post" action="{% url 'information:comments' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="page" value="{{ request.GET.page }}">
            <button type="submit" class="btn btn-sm btn-success m-1">Отправить</button>
        </form>
    {% endif %}
{% else %}
    <h1 class="text-center m-2 text-primary">Отзывы наших клиентов</h1>
    <h5 class="text-center m-2">Вы сможете оставить свой отзыв после регистрации</h5>
{% endif %}
<hr>
<h4 class="text-center m-3 text-primary">
    Вы можете ознакомиться со всеми отзывами или выбрать интересующую Вас категорию
</h4>
<div class="row align-items-center">
    <div class="col-md-2 mb-3 align-self-start flex-column
        {% if request.resolver_match.view_name != 'information:comments_category' %}d-none{% endif %}">
            <a href="{% url 'information:comments' %}"
                class="btn btn-success d-md-flex align-items-center">
                <i class="bi bi-arrow-left-circle-fill"></i>
                <span class="ms-2">К списку отзывов</span>
            </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 0 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 0 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Общая оценка</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 1 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 1 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка специалиста</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 2 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 2 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка статьи</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 3 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 3 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка тренинга</span>
        </a>
    </div>
</div>

{% for comment in comments %}
    {% if comment.author == user %}
        <div class="m-1 p-3 rounded" style="background-color: #d4edda;">
    {% else %}
        <div class="bg-light m-1 p-3 rounded">
    {% endif %}
        <div class="d-flex justify-content-between align-items-center mb-2">
            <h6 class="mb-0">
                {% if comment.author.avatar %}
                    <img src="{{ comment.author.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2"
                         style="width: 30px; height: 30px;">
                {% else %}
                    <i class="bi bi-person-fill me-1"></i>
                {% endif %}
                    {% if comment.author.username %}
                        {{ comment.author.username }}
                    {% else %}
                        Пользователь удалён
                    {% endif %}
            </h6>
            <small class="text-muted">
                <i class="bi bi-clock me-1"></i>
                {{ comment.published_date|date:"d M Y H:i" }}
            </small>
        </div>
        <small class="text-muted">
            <i class="bi bi-list me-1"></i>
            {{ comment.get_category_display }}
        </small>
        <div class="mb-2">{{ comment.text }}</div>
    </div>
    {% include 'answer/comment_answer_include.html' %}
{% endfor %}

information/templates/comment/comment_for_personal_include.html
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

<h4 class="text-center m-2 text-primary">Отзывы пользователей:</h4>
<div class="row align-items-center">
    <div class="col-md-2 mb-3 align-self-start flex-column
        {% if request.resolver_match.view_name != 'information:comments_category' %}d-none{% endif %}">
            <a href="{% url 'information:comments' %}"
                class="btn btn-success d-md-flex align-items-center">
                <i class="bi bi-arrow-left-circle-fill"></i>
                <span class="ms-2">К списку отзывов</span>
            </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 0 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 0 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Общая оценка</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 1 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 1 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка специалиста</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 2 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 2 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка статьи</span>
        </a>
    </div>
    <div class="col-md-2 mb-3 align-self-start d-flex flex-column">
        <a href="{% url 'information:comments_category' 3 %}"
            class="btn {% if request.resolver_match.view_name == 'information:comments_category' and request.resolver_match.kwargs.category == 3 %}btn-primary
            {% else %}btn-info{% endif %} btn-block mb-2">
            <span>Оценка тренинга</span>
        </a>
    </div>
</div>
    {% for comment in comments %}
        <div class="bg-light other-comment mb-3 p-3 rounded">
            <div class="d-flex justify-content-between align-items-center mb-2">
                <h6 class="mb-0">
                    {% if comment.author.avatar %}
                        <img src="{{ comment.author.avatar.url }}" alt="Avatar" class="rounded-circle img-fluid me-2"
                             style="width: 30px; height: 30px;">
                    {% else %}
                        <i class="bi bi-person-fill me-1"></i>
                    {% endif %}
                    {% if comment.author.username %}
                        {{ comment.author.username }}
                    {% else %}
                        Пользователь удалён
                    {% endif %}
                </h6>
                <small class="text-muted">
                    <i class="bi bi-clock me-1"></i>{{ comment.published_date|date:"d M Y H:i" }}
                </small>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-2">
                <small class="text-muted">
                    <i class="bi bi-list me-1"></i>
                    {{ comment.get_category_display }}
                </small>
                <small class="text-muted">
                    <i class="bi {% if comment.status == 0 %}bi-exclamation-circle text-warning
                                 {% elif comment.status == 1 %}bi bi-x-circle text-danger
                                 {% else %} bi bi-check-circle text-success
                                 {% endif %} me-1"></i>
                    {{ comment.get_status_display }}
                </small>
            </div>
            <div class="mb-2">{{ comment.text }}</div>
            <button class="btn btn-sm btn-info reply-button" data-comment-id="{{ comment.id }}">
                <i class="bi bi-reply"></i> Ответить
            </button>
                <div class="reply-form" id="reply-form-{{ comment.id }}" style="display: none;">
                    <form method="post" action="{% url 'information:answers_comment' %}">
                        {% csrf_token %}
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        {{ answer_form.as_p }}
                        <input type="hidden" name="page" value="{{ request.GET.page }}">
                        <button type="submit" class="btn btn-success">Отправить</button>
                        <button type="button" class="btn btn-danger cancel-button">Отмена</button>
                    </form>
                </div>
                {% include 'answer/comment_answer_include.html' %}
        </div>
    {% endfor %}