harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from information.views import *
from events.views import *
from tests.views import *
from users.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('information/', include('information.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('tests/', include('tests.urls')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_404_view

users/urls.py
from django.urls import path, reverse_lazy
from users.views import *
from information.views import *
from events.views import *
from tests.views import *
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('specialists/', SpecialistsView.as_view(), name='specialists'),
    path('specialists/<int:pk>/', SpecialistDetailView.as_view(), name='specialist_detail'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('personal/<int:pk>/', PersonalDetailView.as_view(), name='personal'),
    path('personal/<int:pk>/update/', PersonalUpdateView.as_view(), name='personal_update'),
    path('change-password-personal/', ChangePasswordPersonalView.as_view(), name='change_password_personal'),
    path('client/<int:pk>/comments/', ClientCommentView.as_view(), name='client_comments'),
    path('client/<int:pk>/consultations/', ClientConsultationView.as_view(), name='client_consultations'),
    path('client/<int:pk>/trainings/', ClientTrainingView.as_view(), name='client_trainings'),
    path('client/<int:pk>/testing/', ClientTestsView.as_view(), name='client_testing'),

    path("password-reset/", auth_views.PasswordResetView.as_view(
            template_name="all_users/password_reset_form.html",
            email_template_name="all_users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ), name="password_reset",
    ),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
            template_name="all_users/password_reset_done.html"
        ), name="password_reset_done",
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
            template_name="all_users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ), name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
            template_name="all_users/password_reset_complete.html",
        ), name="password_reset_complete",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db import models
from tinymce.models import HTMLField


class MyUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='avatars/users',
        blank=True,
        null=True,
        verbose_name='Аватар'
    )
    date_birth = models.DateField(
        blank=True,
        null=True,
        default=None,
        verbose_name='Дата рождения'
    )
    phone = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Телефон'
    )
    job_title = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Должность'
    )
    job_speciality = HTMLField(
        blank=True,
        null=True,
        verbose_name='Направления работы'
    )

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Education(models.Model):
    STATUS_CHOICES = [
        (1, 'Высшее образование'),
        (2, 'Повышение квалификации'),
        (3, 'Семинар'),
        (4, 'Обучающий курс'),
        (0, 'Другое'),
    ]
    educational_institution = models.CharField(
        max_length=200,
        verbose_name='Учебное заведение'
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
        verbose_name='Статус'
    )
    speciality = models.TextField(
        verbose_name='Специальность'
    )
    year = models.CharField(
        max_length=4,
        verbose_name='Год окончания'
    )
    photo = models.ImageField(
        upload_to='diplomes/',
        blank=True,
        null=True,
        verbose_name=''
    )
    psychologist = models.ForeignKey(
        'users.MyUser',
        on_delete=models.CASCADE,
        related_name='psychologist',
        verbose_name='Психолог'
    )

    def __str__(self):
        return f'{self.educational_institution} ({self.status}) - {self.year}'

    class Meta:
        verbose_name = "Образование"
        verbose_name_plural = "Образование"

users/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model
from django import forms
from .models import *


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите email'}),
        label='Email'
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}),
        label='Имя пользователя'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}),
        label='Подтверждение пароля'
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя или email'}),
        label='Имя пользователя'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}),
        label='Пароль'
    )


class ClientUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'first_name', 'last_name', 'date_birth', 'email', 'phone', 'avatar']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
            'avatar': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email


class PersonalUpdateForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'date_birth', 'email', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'max_length': 150}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'max_length': 254}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'max_length': 20}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if MyUser.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует")
        return email

users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from users.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, TemplateView, CreateView, UpdateView, ListView, DetailView
from django.views.generic.edit import FormMixin
from .forms import *
from information.urls import *
from django.utils.http import urlencode
from urllib.parse import unquote
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.views import View

menu = [
    {"title": "Главная", "alias": "main", "icon": "bi-house"},
    {"title": "Наши специалисты", "alias": "users:specialists", "icon": "bi-person"},
    {"title": "Советы психолога", "alias": "information:articles", "icon": "bi-chat-dots"},
    {"title": "Тестирование", "alias": "tests:testing", "icon": "bi-ui-checks-grid"},
    {"title": "Консультации", "alias": "events:consultations", "icon": "bi-clipboard"},
    {"title": "Тренинги", "alias": "events:trainings", "icon": "bi-briefcase"},
    {"title": "Отзывы клиентов", "alias": "information:comments", "icon": "bi-list-stars"},
    {"title": "Ваши предложения", "alias": "information:offers", "icon": "bi-lightbulb"}
]


class RegisterView(View):
    template_name = 'all_users/register.html'

    def get(self, request):
        form = UserRegisterForm()
        return render(request, self.template_name, {'form': form, 'menu': menu})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Регистрация прошла успешно! Вы можете войти.')
            return redirect('users:login')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибки!')
        return render(request, self.template_name, {'form': form, 'menu': menu})


class LoginView(View):
    template_name = 'all_users/login.html'

    def get(self, request):
        form = UserLoginForm()
        return render(request, self.template_name, {'form': form, 'menu': menu})

    def post(self, request):
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Добро пожаловать, {user.username}!')
                return redirect('main')
            else:
                messages.error(request, 'Неверные учетные данные. Попробуйте снова.')
        return render(request, self.template_name, {'form': form, 'menu': menu})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'Вы вышли из системы.')
        return redirect('main')


class SpecialistsView(ListView):
    model = MyUser
    template_name = 'personal/specialists.html'
    context_object_name = 'specialists'

    def get_queryset(self):
        return MyUser.objects.filter(is_staff=True, is_superuser=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'users:specialists'
        return context


class SpecialistDetailView(DetailView):
    model = MyUser
    template_name = 'personal/specialist_detail.html'
    context_object_name = 'specialist'

    def get_queryset(self):
        return MyUser.objects.prefetch_related('psychologist')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['page_alias'] = 'users:specialists'
        context['education'] = self.object.psychologist.all()
        return context


class ClientDetailView(DetailView):
    model = MyUser
    template_name = 'client/client.html'
    context_object_name = 'client'

    def get_queryset(self):
        return MyUser.objects.all()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user:
            messages.error(request, 'Не надо подсматривать личные данные другого человека!!!')
            return redirect(reverse('users:client', kwargs={'pk': request.user.pk}))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = MyUser
    form_class = ClientUpdateForm
    template_name = 'client/client_update.html'

    def get_success_url(self):
        return reverse_lazy('users:client', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user:
            return redirect(reverse('users:client_update', kwargs={'pk': request.user.pk}))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context

    def form_valid(self, form):
        new_avatar = form.cleaned_data.get('avatar')
        if new_avatar:
            form.instance.avatar = new_avatar
        else:
            form.instance.avatar = self.get_object().avatar
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'client/change_password.html'

    def get_success_url(self):
        return reverse_lazy('users:client_update', kwargs={'pk': self.request.user.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context


class PersonalDetailView(DetailView):
    model = MyUser
    template_name = 'personal/personal.html'
    context_object_name = 'personal'

    def get_queryset(self):
        return MyUser.objects.all()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user:
            return redirect(reverse('users:personal', kwargs={'pk': request.user.pk}))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context


class PersonalUpdateView(LoginRequiredMixin, UpdateView):
    model = MyUser
    form_class = PersonalUpdateForm
    template_name = 'personal/personal_update.html'

    def get_success_url(self):
        return reverse_lazy('users:personal', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object != request.user:
            return redirect(reverse('users:personal_update', kwargs={'pk': request.user.pk}))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class ChangePasswordPersonalView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'personal/change_password_personal.html'

    def get_success_url(self):
        return reverse_lazy('users:personal_update', kwargs={'pk': self.request.user.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        return context

users/templates/personal/change_password_personal.html
{% extends 'personal/personal.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Смена пароля {{ user.username }}
{% endblock %}

{% block personal_content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="text-center">Смена пароля</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <a href="{% url 'users:personal_update' user.pk %}" class="btn btn-danger">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/personal/personal.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    {{ personal.username }}
{% endblock %}

{% block content %}
<h1 class="text-center m-1 text-success fst-italic">Ваш личный кабинет</h1>
<div class="container mx-auto mb-2">
    <div class="row align-items-center">
        {% if user.avatar %}
            <div class="col-md-3 mb-3 align-self-start">
                <img src="{{ user.avatar.url }}" alt="Avatar" class="img-fluid rounded">
            </div>
        {% endif %}
        <div class="{% if user.avatar %}col-md-6{% else %}col-9{% endif %} align-self-start">
            {% block personal_content %}
            <div class="row align-items-center">
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Имя пользователя</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{ personal.username }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Имя</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if personal.first_name %}
                                <p class="card-text">{{ personal.first_name }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Фамилия</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if personal.last_name %}
                                <p class="card-text">{{ personal.last_name }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Дата рождения</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if personal.date_birth %}
                                <p class="card-text">{{ personal.date_birth }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Адрес электронной почты</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if personal.email %}
                                <p class="card-text">{{ personal.email }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-5 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-success fst-italic">Телефон</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 mb-3 align-self-start">
                    <div class="card">
                        <div class="card-body">
                            {% if personal.phone %}
                                <p class="card-text">{{ personal.phone }}</p>
                            {% else %}
                                <p class="card-text text-danger">Информация отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endblock%}
        </div>
        {% include 'personal/personal_menu_include.html' %}
    </div>
</div>
{% endblock %}

users/templates/personal/personal_menu_include.html
<div class="col-md-3 mb-3 align-self-start d-flex flex-column">
    <a href="{% url 'users:personal' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:personal' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-house m-2"></i>Личный кабинет</span>
    </a>
    <a href="{% url 'admin:index' %}"
       class="btn btn-info btn-block mb-2" target="_blank" rel="noopener noreferrer">
       <span><i class="bi bi-gear m-2"></i>Админпанель</span>
    </a>
    <a href="{% url 'users:personal_update' user.pk %}"
       class="btn {% if request.resolver_match.view_name == 'users:personal_update' %}btn-primary
       {% else %}btn-info{% endif %} btn-block mb-2">
       <span><i class="bi bi-pencil m-2"></i>Редактировать данные</span>
    </a>
</div>

users/templates/personal/personal_update.html
{% extends 'personal/personal.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Редактирование {{ user.username }}
{% endblock %}

{% block personal_content %}
<div class="card">
    <div class="card-header">
        <h4 class="card-text text-center text-success fst-italic">Измените необходимые данные</h4>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label fst-italic">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-success m-2">Сохранить</button>
                <a href="{% url 'users:personal' user.pk %}" class="btn btn-danger m-2">Отмена</a>
            </div>
        </form>
        <a href="{% url 'users:change_password_personal' %}" class="btn btn-info m-2">Изменить пароль</a>
    </div>
</div>
{% endblock %}

users/templates/personal/specialist_detail.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    {{ specialist.username }}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center">
    <a href="{% url 'users:specialists' %}" class="btn btn-success d-none m-2 d-md-flex align-items-center">
        <i class="bi bi-arrow-left-circle-fill fs-4"></i>
        <span class="ms-2">К списку специалистов</span>
    </a>
    <a href="{% url 'users:specialists' %}" class="btn btn-success d-flex m-2 d-md-none align-items-center">
        <i class="bi bi-arrow-left-circle-fill fs-4"></i>
    </a>
</div>
<h1 class="text-center m-1 text-success fst-italic">{{ specialist.first_name }} {{ specialist.last_name }}</h1>
<div class="container mx-auto mb-2">
    <div class="row align-items-center">
        {% if specialist.avatar %}
            <div class="col-md-3 mb-3 align-self-start">
                <img src="{{ specialist.avatar.url }}" alt="Avatar" class="img-fluid rounded">
            </div>
        {% endif %}
        <div class="{% if specialist.avatar %}col-md-9{% else %}col-12{% endif %} align-self-start">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-success">Специализация</h5>
                    <p class="card-text">{{ specialist.job_title }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-success">Основные направления работы</h5>
                    <p class="card-text">{{ specialist.job_speciality|safe }}</p>
                </div>
            </div>
            {% for item in education %}
                <div class="card">
                <div class="card-body">
                    <h6 class="card-title">{{ item.get_status_display }}</h6>
                    <p class="card-text">{{ item.year }} г. - {{ item.educational_institution }} -
                        <span class="card-text fst-italic">"{{ item.speciality }}"</span>
                    </p>
                    {% if item.photo %}
                        <div class="col-md-3 mb-3 align-self-start">
                            <img src="{{ item.photo.url }}" alt="Photo" class="img-fluid rounded">
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

users/templates/personal/specialists.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/styles.css'%}" />
{% endblock %}

{% block title %}
    Наши специалисты
{% endblock %}

{% block content %}
<h1 class="text-center m-2 text-primary">У нас только высококвалифицированные специалисты</h1>
<div class="row row-cols-1 row-cols-md-3 g-4 m-2">
    {% for specialist in specialists %}
        <div class="col">
            <div class="card">
                <h4 class="card-title text-center p-1">
                    {{ specialist.first_name }} {{ specialist.last_name }}
                </h4>
                {% if specialist.avatar %}
                    <div class="d-flex justify-content-center">
                        <img src="{{ specialist.avatar.url }}" alt="Avatar" class="img-fluid rounded"
                             style="max-width: 250px;">
                    </div>
                {% else %}
                    <div class="d-flex justify-content-center">
                        <span class="bg-success text-white d-flex align-items-center justify-content-center m-2 fs-1"
                              style="width: 250px; height: 250px; border-radius: 50%;">
                            <span>{{ specialist.first_name|slice:":1" }}{{ specialist.last_name|slice:":1" }}</span>
                        </span>
                    </div>
                {% endif %}
                <h5 class="card-text text-center p-1 text-muted">{{ specialist.job_title }}</h5>
                <a href="{% url 'users:specialist_detail' specialist.id %}" class="btn btn-success">
                    <i class="bi bi-card-list"></i>
                    <span class="d-none d-sm-inline">Подробнее</span>
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}